/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package maven_demo;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static double divide(double a, double b) throws ZeroException {
        if (b == 0) {
            throw new ZeroException();
        }
        return a / b;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
