/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void main(String[] args) {
      IntCalculator intCalculator = new IntCalculator();
      System.out.println(intCalculator.add(10, -9));
      System.out.println(intCalculator.computeFromString("5 * -10"));
      System.out.println(intCalculator.computeFromString("-5 + +10"));
      System.out.println(intCalculator.computeFromString("-50 / -10"));
      System.out.println(intCalculator.computeFromString("-5 - 10"));
      // System.out.println(intCalculator.computeFromStandardInput());  
      
    }
}
