/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package maven_demo;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appTest1() {
        try {
            assertEquals(null, App.getQuestion(null));
        } catch (Exception e) {
            assertEquals(true, true);
        }
    }

    @Test
    void appTest2() {
        assertDoesNotThrow(() -> {
            assertEquals("ça va ?", App.getQuestion("ça va"));
        });
    }

    @Test
    void appTest3() {
        assertDoesNotThrow(() -> {
            assertEquals("?", App.getQuestion(""));
        });
    }
}
