/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package maven_demo;

public class App {
    public static String getQuestion(String sentence) throws Exception {
        if (sentence == null) {
            throw new Exception();
        }
        if (sentence.length() == 0) {
            throw new Exception("Oups");
        }
        if (sentence.charAt(sentence.length() - 1) == '?') {
            throw new Exception("Aie");
        }
        return sentence + "?";
    }
}